name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            name: ğŸ§ Linux
            build_command: cmake --build build -- -j
            test_command: ./git-kudos
          - os: macos-latest
            name: ğŸ MacOS
            build_command: cmake --build build -- -j
            test_command: ./git-kudos
          - os: windows-latest
            name: ğŸªŸ Windows
            build_command: cmake --build . --config Release
            test_command: ./Release/git-kudos.exe

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: actions/setup-cmake@v3

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build CMake
      run: ${{ matrix.build_command }}

    - name: Test
      run: ${{ matrix.test_command }}
